version: "3"
services:
  # postgres:
  #   image: "postgres:latest"
  #   environment:
  #     - POSTGRES_PASSWORD=postgres_password
  # redis:
  #   image: "redis:latest"
  nginx:
    image: akashskynet009/react-multi-nginx:latest
    depends_on:
      - api
      - client
    restart: always
    # build:
    #   dockerfile: Dockerfile
    #   context: ./nginx
    # ports:
    #   - "3050:80"
  server:
    image: akashskynet009/react-multi-server:latest
    # build:
    #   dockerfile: Dockerfile
    #   context: ./server
    # volumes:
    #   - /app/node_modules
    #   - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    image: akashskynet009/react-multi-client:latest
    mem_limit: 128m
    hostname: client
    # environment:
    #   - WDS_SOCKET_PORT=0
    # build:
    #   dockerfile: Dockerfile
    #   context: ./client
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app
  worker:
    image: akashskynet009/react-multi-worker:latest
    # build:
    #   dockerfile: Dockerfile
    #   context: ./worker
    # volumes:
    #   - /app/node_modules
    #   - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379