version: "3"
services:
  client:
    image: "704126795178.dkr.ecr.us-west-1.amazonaws.com/react-multi-client:latest"
    mem_limit: 128m
    hostname: client
  server:
    image: "704126795178.dkr.ecr.us-west-1.amazonaws.com/react-multi-server:latest"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "704126795178.dkr.ecr.us-west-1.amazonaws.com/react-multi-worker:latest"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "704126795178.dkr.ecr.us-west-1.amazonaws.com/react-multi-nginx:latest"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"